### ISSUE TITLE
PaperMerge?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [linuxserver/reverse-proxy-confs#255]
Does anyone have any experience with Papermerge? I'm using the LSIO Papermerge container that exposes port 8000 in the container, so I created this:

```
location ^~ /papermerge {
    # enable the next two lines for http auth
    #auth_basic "Restricted";
    #auth_basic_user_file /config/nginx/.htpasswd;

    # enable the next two lines for ldap auth, also customize and enable ldap.conf in the default conf
    #auth_request /auth;
    #error_page 401 =200 /ldaplogin;

    # enable for Authelia, also enable authelia-server.conf in the default site config
    #include /config/nginx/authelia-location.conf;

    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_app papermerge;
    set $upstream_port 8000;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    
    # enable the next two lines to allow in organizr iframes
    proxy_hide_header X-Frame-Options;
    proxy_hide_header Content-Security-Policy;
}
```

but I just get a 404:

> Not Found
> The requested resource was not found on this server.

I've googled thinking maybe papermerge needs a base/root URL in it's config but came up empty?

**Comment by Erriez** [comment]
@YouveGotMeowxy I've papermerge subdomain working without setting a base/root URL:

**config/nginx/proxy-confs/papermerge.subdomain.conf**
```yaml
## Version 2021/02/08
# make sure that your dns has a cname set for papermerge and that your papermerge container is not using a base url

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name papermerge.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    # enable for Authelia
    #include /config/nginx/authelia-server.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /ldaplogin;

        # enable for Authelia
        #include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_app papermerge;
        set $upstream_port 8000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }
}
```

**docker-compose.yml**
```yaml
version: '3'

services:
  papermerge:
    # Username: admin
    # Password: admin
    image: ghcr.io/linuxserver/papermerge
    container_name: papermerge
    restart: always
    environment:
      - PUID=$DOCKER_UID
      - PGID=$DOCKER_GID
      - TZ=${TZ}
    volumes:
      - ${VOLUME_DIR}/papermerge/config:/config
      - ${VOLUME_DIR}/papermerge/data:/data
 
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    restart: always
    ports:
      - 80:80
      - 443:443
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=$DOCKER_UID
      - PGID=$DOCKER_GID
      - EMAIL=${SWAG_EMAIL}
      - URL=${ROOT_DOMAIN}
      - SUBDOMAINS=${SWAG_SUBDOMAINS}
      - VALIDATION=${SWAG_VALIDATION}
      - DNSPLUGIN=${SWAG_DNSPLUGIN}
      - ONLY_SUBDOMAINS=${SWAG_ONLY_SUBDOMAINS}
      - TZ=${TZ}
    volumes:
      - ${VOLUME_DIR}/swag/config:/config
```
