### ISSUE TITLE
add new amule.subdomain.conf

### ISSUE THREAD

**Issue by wswv** [linuxserver/reverse-proxy-confs#284]
Today I tested amule docker which from tchabaud/amule and it works, then I tried to modified a template of subdomain for amule in SWAG. it works too. the modified file looks like below:
-------------------------------------start-------------------------------------------------------------
```
## REMOVE THIS LINE BEFORE SUBMITTING: The structure of the file (all of the existing lines) should be kept as close as possible to this template.
## REMOVE THIS LINE BEFORE SUBMITTING: Look through this file for <tags> and replace them. Review other sample files to see how things are done.
## REMOVE THIS LINE BEFORE SUBMITTING: The comment lines at the top of the file (below this line) should explain any prerequisites for using the proxy such as DNS or app settings.
## make sure that your dns has a cname set for <container_name> and that your <container_name> container is not using a base url

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name amule.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    # enable for Authelia
    #include /config/nginx/authelia-server.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /ldaplogin;

        # enable for Authelia
        #include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_app amule;
        set $upstream_port 4711;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

        # REMOVE THIS LINE BEFORE SUBMITTING: Additional proxy settings such as headers go below this line, leave the blank line above.
    }

    # REMOVE THIS LINE BEFORE SUBMITTING: Some proxies require one or more additional location blocks for things like API or RPC endpoints.
    # REMOVE THIS LINE BEFORE SUBMITTING: If the proxy you are making a sample for does not require an additional location block please remove the commented out section below.
    # location ~ (/<container_name>)?/api {
    #     include /config/nginx/proxy.conf;
    #     resolver 127.0.0.11 valid=30s;
    #     set $upstream_app <container_name>;
    #     set $upstream_port <port_number>;
    #     set $upstream_proto <http or https>;
    #     proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    #
    #     # REMOVE THIS LINE BEFORE SUBMITTING: Additional proxy settings such as headers go below this line, leave the blank line above.
    # }
}
```
--------------------------end--------------------------------

at the same time, the docker-compose file looks like below:
-----------------------docker-compose.yaml------------------
```
version: '2'
services:
  amule:
    image: tchabaud/amule
    ports:
      - "4711:4711"7#web
      - "4662:4662"#amule used, need to expose to WAN
      - "4672:4672/udp"#amule used, need to expose to WAN
    environment:
      - PUID=1000
      - GUID=1000
    volumes:
      - ./conf:/home/amule/.aMule
      - ./amule/data:/incoming
      - ./amule/tmp:/temp
networks:
  default:
    external: 
      name: SWAG
```
----------------docker-compose.end---------------

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
