### ISSUE TITLE
Duplicati login path does not work with subfolder

### ISSUE THREAD

**Issue by cpaucar3** [linuxserver/reverse-proxy-confs#382]
Ubuntu 18.04.1
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

Docker compose duplicati section
```
   duplicati:
     container_name: duplicati
     environment:
       PGID: ${PGID}
       PUID: ${PUID}
       TZ: ${TZ}
     image: ghcr.io/linuxserver/duplicati
     networks:
       smarthome:
         ipv4_address: 172.18.0.15
     restart: always
     volumes:
     - ${USERDIR}/duplicati:/config
     - ${USERDIR}:/source
```
When I click to login it takes me to the wrong URL and I have to manually add in the subfolder name.
Expected:
`https://mydomain.com/duplicati/login.html?v=2.0.6.3`
Observed:
`https://mydomain.com/login.html?v=2.0.6.3`
I'm using the latest Docker image and I did not modify `duplicati.subfolder.conf`.
