### ISSUE TITLE
Seafile sample config file gives 502 bad gateway

### ISSUE THREAD

**Issue by frenicohansen** [linuxserver/reverse-proxy-confs#425]
I used this docker-compose file (https://download.seafile.com/d/320e8adf90fa43ad8fee/files/?p=/docker/docker-compose.yml) to deploy seafile. Seafile has already nginx and lets encrypt included in this container, but I want to hide it behind SWAG. 
I tried seafile.subdomain.config but, gives me a 502 bad gateway error. Also tried the config file from this branch https://github.com/linuxserver/reverse-proxy-confs/tree/seafile-patch. But gives me this error.
```
Bad Request
Contradictory scheme headers
```

**Comment by j0nnymoe** [comment]
As I mentioned on your previous comment, this link will explain the 502 errors https://docs.linuxserver.io/general/swag#502

**Comment by frenicohansen** [comment]
Sorry, didn't get any notification from github about your reply. I have read the link you gave, I still don't know where I did wrong though. This is my docker-compose file for seafile

```
version: '2.0'
services:
  memcached:
    image: memcached:alpine
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net
          
  seafile:
    image: seafileltd/seafile-mc:9.0.2-arm
    container_name: seafile
#    ports:
#      - "80:80"
#      - "443:443"  # If https is enabled, cancel the comment.
    volumes:
      - ./docker-data/seafile-data:/shared   # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=mariadb
      - DB_ROOT_PASSWD=******  # Requested, the value shuold be root's password of MySQL service.
      - TIME_ZONE=Europe/Berlin  # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_ADMIN_EMAIL=****** # Specifies Seafile admin user, default is 'me@example.com'.
      - SEAFILE_ADMIN_PASSWORD=******     # Specifies Seafile admin password, default is 'asecret'.
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether to use https or not.
      - SEAFILE_SERVER_HOSTNAME=sf.domain.com # Specifies your host name if https is enabled.
    depends_on:
      - memcached
    networks:
      - seafile-net
      - swag-proxy
      - mariadb-net

networks:
  swag-proxy:
    external: true
  mariadb-net:
    external: true
  seafile-net:
```

And this is my proxy config file, I used the one from this branch as my swag container has a wildcard cert already and I don't need seafile to request cert again.
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name sf.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    # enable for Authelia
    #include /config/nginx/authelia-server.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /ldaplogin;

        # enable for Authelia
        #include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app seafile;
        set $upstream_port 80;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
```

- [ ]  The application and SWAG is on the same custom docker network 
- [ ] The container name does not match the application name (in proxxy conf)

**Comment by tubezleb** [comment]
OK so I had the same issue with swag and the last version of the seafile docker image available.
The problem is the seafile docker image already run nginx as reverse proxy inside the container.
So to use swag I choose to bypass the nginx proxy inside the container to directly use the seafile ports (8000 and 8082)

By default seafile listen on localhost so to expose the port 8000 you need to edit the file **gunicorn.conf.py**  from the folder: "/shared/seafile/conf" and replace 
`bind = "127.0.0.1:8000" `
with
`bind = "0.0.0.0:8000"`
and restart the container

Next on the docker compose file you need to expose the ports 8000 and 8082

Here my docker-compose file for seafile
```
........
  db:
    image: mariadb:10.5
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - /home/denis/containers/seafile/db:/var/lib/mysql
      
  memcached:
    image: memcached:1.5.6
    container_name: seafile-memcached
    entrypoint: memcached -m 256

  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    ports:
      - 8000
      - 8082
    volumes:
      - /my/path/seafile-data:/shared
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=
      - TIME_ZONE=America/Montreal
      - PUID=1000
      - PGID=100
      - SEAFILE_ADMIN_EMAIL=admin@admin.net
      - SEAFILE_ADMIN_PASSWORD=
      - SEAFILE_SERVER_HOSTNAME=seafile.domain.com
    depends_on:
      - db
      - memcached
```
and `docker-compose up -d` 

And finally I modified the **seafile.subdomain.conf** like this

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name seafile.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 10m;

    location / {
        include /config/nginx/resolver.conf;
        proxy_pass http://seafile:8000;
        proxy_read_timeout 310s;
        proxy_set_header Host $host;
        proxy_set_header Forwarded "for=$remote_addr;proto=$scheme";
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Connection "";
        proxy_http_version 1.1;

        client_max_body_size 0;
    }

    location /seafhttp {
        include /config/nginx/resolver.conf;
        rewrite ^/seafhttp(.*)$ $1 break;
        proxy_pass http://seafile:8082;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        client_max_body_size 0;
        proxy_connect_timeout  36000s;
        proxy_read_timeout  36000s;
        proxy_request_buffering off;
    }

}
```
And after a restart of the swag container everything looks working fine, I' m sure the file **seafile.subdomain.conf** can be optimized but so fat it' s working for me.
