### ISSUE TITLE
[BUG] Filebot proxy super slow

### ISSUE THREAD

**Issue by YouveGotMeowxy** [linuxserver/reverse-proxy-confs#517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using the current RP with filebot (rednoah's [official version](https://hub.docker.com/r/rednoah/filebot#filebot-xpra)) (I had to change the ports in the RP to 5454 for his container; not sure which container the RP was created for) the WebUI is super slow, and even unusable due to a poor connection according to FB's logs. Lots of GUI freezing, and super-long delays waiting for the GUI to free up and respond again.

I am able to compare it directly with the non-proxied webui and it's definitely the proxy; non-proxy is very fast.

### Steps To Reproduce

This is my Compose:

```
  filebot:
    image: 'rednoah/filebot:xpra'
    hostname: 'filebot'
    environment:
      TZ: 'America/Chicago'
      PUID: '1000'
      PGID: '1000'
      JAVA_OPTS: '-Xmx1g'
    volumes:
      - '/opt/docker/configs/filebot:/data:rw'
      - '/mnt/e/Media/.downloads/.filebot/media:/volume1:rw'
    ports:
      - '5454:5454'
    networks:
      - 'htpc'
    deploy:
        mode: 'replicated'
        replicas: 1
        placement:
          constraints:
            - 'node.labels.Main == true'
        resources:
          limits:
            memory: '1G'
        restart_policy:
          condition: 'any'
```
