### ISSUE TITLE
[BUG] OpenBudgeteer loads but has no interaction

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [linuxserver/reverse-proxy-confs#536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The page loads and page changes where the url changes alongwith work fine.

Interactions within the page do not work, i.e. when I click on create account, no pop up is present.
This is not a container issue, as when I go to http://ip:port on which the container is exposed, everything works fine. 

Issue discussed on OpenBudgeteer github - https://github.com/TheAxelander/OpenBudgeteer/issues/133
Developer believes it is a reverse proxy config issue specifically to do with Websocket support. Has provided an nginx proxy conf file - https://github.com/TheAxelander/OpenBudgeteer/issues/133#issuecomment-1448301529

Unable to reconcile the two what is different.

### Expected Behavior

Interactions on the page would also work.

### Steps To Reproduce

Deploy OpenBudgeteer with this config - 

```
version: "3"

networks:
  docker:
    external: true
  openbudgeteer-internal:


services:
  openbudgeteer:
    image: axelander/openbudgeteer
    container_name: openbudgeteer
    ports:
      - 1018:80
    environment:
      - CONNECTION_SERVER=openbudgeteer-mysql
      - CONNECTION_PORT=3306
      - CONNECTION_DATABASE=openbudgeteer
      - CONNECTION_USER=redacted
      - CONNECTION_PASSWORD=redacted
      - CONNECTION_MYSQL_ROOT_PASSWORD=redacted
      - APPSETTINGS_CULTURE=en-GB
      - APPSETTINGS_THEME=vapor
    depends_on:
      - mysql
    networks:
      - docker
      - openbudgeteer-internal

  mysql:
    image: mysql
    container_name: openbudgeteer-mysql
    environment:
      MYSQL_ROOT_PASSWORD: redacted
    volumes:
      - redacted/data:/var/lib/mysql
    networks:
      - docker
      - openbudgeteer-internal

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: openbudgeteer-phpmyadmin
    links:
      - mysql:db
    ports:
      - 7996:80
    networks:
      - docker
      - openbudgeteer-internal
```

Reverse proxied with this config - 

```
## Version 2023/02/05
# REMOVE THIS LINE BEFORE SUBMITTING: The structure of the file (all of the existing lines) should be kept as close as possible to this template.
# REMOVE THIS LINE BEFORE SUBMITTING: Look through this file for <tags> and replace them. Review other sample files to see how things are done.
# REMOVE THIS LINE BEFORE SUBMITTING: The comment lines at the top of the file (below this line) should explain any prerequisites for using the proxy such as DNS or app settings.
# make sure that your <container_name> container is named <container_name>
# make sure that your dns has a cname set for <container_name>

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name openbudgeteer.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth (requires ldap-location.conf in the location block)
    #include /config/nginx/ldap-server.conf;

    # enable for Authelia (requires authelia-location.conf in the location block)
    #include /config/nginx/authelia-server.conf;

    # enable for Authentik (requires authentik-location.conf in the location block)
    #include /config/nginx/authentik-server.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable for ldap auth (requires ldap-server.conf in the server block)
        #include /config/nginx/ldap-location.conf;

        # enable for Authelia (requires authelia-server.conf in the server block)
        #include /config/nginx/authelia-location.conf;

        # enable for Authentik (requires authentik-server.conf in the server block)
        #include /config/nginx/authentik-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app openbudgeteer;
        set $upstream_port 80;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

        # REMOVE THIS LINE BEFORE SUBMITTING: Additional proxy settings such as headers go below this line, leave the blank line above.
    }

    # REMOVE THIS LINE BEFORE SUBMITTING: Some proxies require one or more additional location blocks for things like API or RPC endpoints.
    # REMOVE THIS LINE BEFORE SUBMITTING: If the proxy you are making a sample for does not require an additional location block please remove the commented out section below.
    # location ~ (/<container_name>)?/api {
    #     include /config/nginx/proxy.conf;
    #     include /config/nginx/resolver.conf;
    #     set $upstream_app <container_name>;
    #     set $upstream_port <port_number>;
    #     set $upstream_proto <http or https>;
    #     proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    #
    #     # REMOVE THIS LINE BEFORE SUBMITTING: Additional proxy settings such as headers go below this line, leave the blank line above.
    # }
}

```
