### ISSUE TITLE
[BUG] FreshRSS subfolder links go to 404

### ISSUE THREAD

**Issue by SimFre** [linuxserver/reverse-proxy-confs#544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When logging in to FreshRSS after setting it up with the subfolder configuration, it sends me to domain.tld/i/?rid=nnnnnnnn.

Can't find a subfolder configuration on FreshRSS, so perhaps this is a no-go until it's implemented in that project?

### Expected Behavior

Should be directed to domain.tld/freshrss/i/?rid=nnnnnnnn.

### Steps To Reproduce
1. Go to domain.tld/freshrss, get login form
2. Enter credentials, submit
3. Gets directed to domain.tld/i/?rid=nnnnnnnn in root folder instead of its subfolder.

freshrss.subfolder.conf:
```
## Version 2023/02/05
# make sure that your freshrss container is named freshrss
# freshrss does not require a base url setting

location /freshrss {
    return 301 $scheme://$host/freshrss/;
}

location ^~ /freshrss/ {
    # enable the next two lines for http auth
    #auth_basic "Restricted";
    #auth_basic_user_file /config/nginx/.htpasswd;

    # enable for ldap auth (requires ldap-server.conf in the server block)
    include /config/nginx/ldap-location.conf;

    # enable for Authelia (requires authelia-server.conf in the server block)
    #include /config/nginx/authelia-location.conf;

    # enable for Authentik (requires authentik-server.conf in the server block)
    #include /config/nginx/authentik-location.conf;

    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_app freshrss;
    set $upstream_port 80;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    rewrite /freshrss(.*) $1 break;
    proxy_buffering off;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_cookie_path / "/; HTTPOnly; Secure";
    proxy_set_header Authorization $http_authorization;
    proxy_pass_header Authorization;
}
```

docker-compose.yml:
```
version: "3"
services:
  freshrss:
    container_name: freshrss
    domainname: domain.tld
    environment:
      - PUID=30000
      - PGID=10005
      - TZ=Europe/Berlin
      - UMASK=002
    expose:
      - 80/tcp
    hostname: freshrss
    image: lscr.io/linuxserver/freshrss:latest
    networks:
      br:
        aliases:
          - freshrss
    restart: unless-stopped
    volumes:
      - /docker/config/freshrss:/config
networks:
  br:
    external: true
```
