### ISSUE TITLE
jDownloader 2

### ISSUE THREAD

**Issue by STaRDoGG** [linuxserver/reverse-proxy-confs#74]
I'm still not the most familiar with Nginx; I'm wrasslin with this RP at the moment. It's close but no cigar. It'll load but none of the assets are loading. No CSS, etc.

I thought that usually meant that a base URL needed to be used, but in this container I see no mention of it needing one. I'm using this container, and basing my RP on the example he has there for the subfolder + trying to follow your RP patterns as well: 

https://hub.docker.com/r/jlesage/jdownloader-2

Here's what I have so far:

```
location /jdownloader-2 {
    return 301 $scheme://$http_host/jdownloader-2/;
}

location /jdownloader-2/ {
    # enable the next two lines for http auth
    #auth_basic "Restricted";
    #auth_basic_user_file /config/nginx/.htpasswd;

    # enable the next two lines for ldap auth, also customize and enable ldap.conf in the default conf
    #auth_request /auth;
    #error_page 401 =200 /login;

    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_jdownloader_2 jdownloader-2;
    proxy_pass http://$upstream_jdownloader_2:5800/;
    #proxy_set_header X-Scheme $scheme;
    #proxy_set_header X-Script-Name /jdownloader-2;

    location /jdownloader-2/websockify {
        proxy_pass http://$upstream_jdownloader_2:5800/websockify/;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_read_timeout 86400;
    }
}
```
The console is showing a bunch of these:

> Resource interpreted as Stylesheet but transferred with MIME type text/html

> Uncaught SyntaxError: Unexpected token .

I haven't gotten to the `websockify` stuff yet; I just have that there for the moment because he has it in his sample.

I have a feeling it's something simple that's slipping by me. Anyone able spot anything wrong?

**Comment by STaRDoGG** [comment]
**Update:**

I got it working _as long as I expose a port to the host_, but not if I don't. I'd like to wrap this up finally, if anyone can help out? (I opened this issue almost 7 months ago).

Here's my current RP config:

```
#

location /jdownloader {
    # Added in case user also just wants to use 'jdownloader'
    return 301 $scheme://$host/jdownloader-2/;
}

location /jdownloader-2 {
    return 301 $scheme://$host/jdownloader-2/;
}

location /jdownloader-2/ {
    # enable the next two lines for http auth
    #auth_basic "Restricted";
    #auth_basic_user_file /config/nginx/.htpasswd;

    # enable the next two lines for ldap auth, also customize and enable ldap.conf in the default conf
    #auth_request /auth;
    #error_page 401 =200 /login;

    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_jdownloader_2 jdownloader-2;
    proxy_pass http://$upstream_jdownloader_2:5800/;
    proxy_set_header X-jDownloader-Base "/jdownloader-2/";
}

location /jdownloader-2/websockify {
    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_jdownloader_2 jdownloader-2;
    proxy_pass http://$upstream_jdownloader_2:5800/websockify/;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
}
```

And it works perfect if I expose a port to the host, with this config, and access it directly via it's IP and port (not via the reverse proxy: i.e. http://192.168.0.122:9023):

```
    jdownloader-2:
        container_name: 'jdownloader-2'
        image: 'jlesage/jdownloader-2:latest'
        environment:
        - TZ='America/Chicago'
        - KEEP_APP_RUNNING=1
        - USER_ID=197609
        - GROUP_ID=197121
        restart: unless-stopped
        volumes:
            - 'scotts_jdownloader2_data:/config:rw'
            - '/f/Fetched Media/Unsorted:/output:rw'
        ports:
            - '9023:5800'
        networks:
        - od

networks:
    od:
        external:
            name: my-download
```

If I remove the port, and just try to access via the internal docker network, i.e.:

```
    jdownloader-2:
        container_name: 'jdownloader-2'
        image: 'jlesage/jdownloader-2:latest'
        environment:
        - TZ='America/Chicago'
        - KEEP_APP_RUNNING=1
        - USER_ID=197609
        - GROUP_ID=197121
        restart: unless-stopped
        volumes:
            - 'scotts_jdownloader2_data:/config:rw'
            - '/f/Fetched Media/Unsorted:/output:rw'
        networks:
        - od

networks:
    od:
        external:
            name: my-download
```

I have the letsencrypt container within the same docker network, ("my-download") as the jdownloader-2 container.

Trying to access jdownloader's webui with the above RP config just shows this (no .js, .css files get loaded):

![image](https://user-images.githubusercontent.com/1524526/73574710-01f85580-443c-11ea-8c41-f602c73dcc48.png)


Anyone more schooled in this area than I have any ideas? I'd appreciate it, muy mucho!
